# Générer le TSP

```{r}
library(ggplot2)
library(magrittr)
library(ggrepel)
library(ggpubr)
```
```{r}

```

# Afficher le problème

```{r}

```
```{r}
afficher_tournee <- function(TSP, T) {
	p <- afficher_plan(TSP)
	edges_list <- c()
	for (i in 1:(length(T)-1)) {
		x <- c(TSP$nodes[as.numeric(T[i]),"x"], TSP$nodes[as.numeric(T[i+1]),"x"])
		y <- c(TSP$nodes[as.numeric(T[i]),"y"], TSP$nodes[as.numeric(T[i+1]),"y"])
		#print(x);print(y)
		loop_input = paste(
			"geom_line(aes(x = c(",
			x[1],", ",x[2],")",
			", y = c(",
			y[1],", ",y[2],")",
			", color = 'black'))",
			sep = ""
		)
		p <- p + eval(parse(text = loop_input))
	}
	return(p)
}
```


# PPV

```{r}
# Calculer le PPV à partir d'un TSP
# Renvoi une liste T avec l'ordre des noeuds visités

PPV <- function(TSP) {
	current <- TSP$warehouse
	T <- c(current)
	nodes <- rownames(TSP$nodes)[rownames(TSP$nodes) != current]
	while (length(nodes) > 0) {
		current <- nodes[which(TSP$D[current,nodes] == min(TSP$D[current,nodes]))]
		T <- append(T, current)
		nodes <- nodes[nodes != current]
	}
	T <- append(T, TSP$warehouse)
	return(T)
}

```

# 2-opt
```{r}
swap_edges <- function(T, u, v) {
	# print(u); print(v); print(T)
	i = which(T[1:(length(T)-1)] == u)
	j = which(T[1:(length(T)-1)] == v)
	# print(i); print(j)
	while (j > i) {
		mid <- T[j]
		T[j] <- T[i]
		T[i] <- mid
		i = i + 1
		j = j - 1
	}
	return(T)
}
```

```{r}
deux_opt <- function(TSP, T, nbrmax = 1000) {
	
	n <- dim(TSP$nodes)[1]
	# print(T)
	SWAP <- TRUE
	nbr = 0
	while (SWAP & nbr < nbrmax + 1) {
		SWAP <- FALSE
		for (i in 2:(n-2)) {
			for (j in (i+1):(n-1)) {
		
				delta <- -TSP$D[T[i-1],T[i]]-TSP$D[T[j],T[j+1]]+
				TSP$D[T[i-1],T[j]] + TSP$D[T[i],T[j+1]]
				# print(paste("i = ",i,", j = ",j,", delta = ",delta))
				if (delta < 0) {
					SWAP = TRUE
					nbr = nbr + 1
					T <- swap_edges(T, T[i], T[j])
					# print(T)
				}
			}
		}
	}
	
	return(T)
}
```

# Calcul cout

```{r}
calcul_cout <- function(TSP, T) {
	sum <- 0
	for (i in 1:(length(T)-1)) {
		sum <- sum + TSP$D[as.numeric(T[i]),as.numeric(T[i+1])]
	}
	return(sum)
}
```

```{r}
enveloppe_convexe <- function(TSP, info = FALSE) {
	
	# Sort une liste de noeud faisant le tour de l'enveloppe convexe
	# # On a les infos suivantes :
	
	n <- length(TSP$nodes[,'x'])
	X <- TSP$nodes[,'x']
	Y <- TSP$nodes[,'y']
	
	# Trouver wini
	w <- 1
	for (i in 2:n) {
		if (Y[i] < Y[w]) {
			w <- i
		}
	}
	# Dans w on a l'indice du premier noeud
	
	# l'angle min à respecter
	Oini <- 0
	# Le point initial A prend la valeur initiale w
	A <- w
	# B prend 0 pour permettre une première itération
	B <- 0
	# On ajoute w à la liste de noeud
	T <- c(w)
	
	while (B != w) {
		B <- A
		O <- Inf
		for (i in (1:n)[1:n != A]) {
			# calcul l'ange entre DAB
			# zd - zA
			ALPHA <- c(1,0)
			BETA <- c(X[i]-X[A],Y[i]-Y[A])
			GAMMA <- c(
				(ALPHA[1]*BETA[1]+ALPHA[2]*BETA[2])/(BETA[1]^2+BETA[2]^2),
				(ALPHA[1]*ALPHA[2]-BETA[1]*BETA[2])/(BETA[1]^2+BETA[2]^2)
			)
			if (GAMMA[2] == 0 & GAMMA[1] < 0) {
				ARGAMMA <- pi
			} else if (GAMMA[1] == 0 & GAMMA[2] == 0) {
				ARGAMMA <- 0
			} else {
				ARGAMMA <- 2 * atan(GAMMA[2]/(GAMMA[1]*sqrt(GAMMA[1]^2+GAMMA[2]^2)))
			}
			
			if (ARGAMMA < O & ARGAMMA > Omin) {
				O <- ARGAMMA
				B <- i
			}
		}
		
		Omin <- O
		T <- c(T, B)
		A <- B
	}
	return(T)
}
```

# Exemple Shamos

```{r}
tsp <- generer_TSP()
afficher_plan(tsp)
```

```{r}
T <- enveloppe_convexe(tsp, info = TRUE); T
```

# Exemple PPV

```{r}
tsp <- generer_TSP()
afficher_plan(tsp)
```

```{r}
T <- PPV(tsp)
```
```{r}
afficher_tournee(tsp, T)
```

```{r}
T
```


```{r}
deux_opt(tsp, T)
```
```{r}
afficher_tournee(tsp, deux_opt(tsp, T))
```

```{r}
tsp <- generer_TSP()
T <- PPV(tsp)
a <- afficher_tournee(tsp, T)
T2 <- deux_opt(tsp, T, nbrmax = Inf)
b <- afficher_tournee(tsp, T2)
```

```{r}
figure <- ggarrange(a, b, ncol = 2, nrow = 1)
figure
```

```{r}
calcul_cout(tsp, T)
calcul_cout(tsp, T2)
```

